Fix a bug that both controllers can not put into one model.
When putting both controllers into one model and compiling the model,
there will be an error:

```text
Error: Input must be a 2-D matrix.
```

This is caused by `Additional data sources`. If both controllers
reference data sources that have variables with the same identifier,
this error will occur.

With moving the variables to model workspace instead of referencing the
data source, this bug is fixed.